YALO_RUN=./yalo.exe -I yalo_config -I ./_build/install/default/lib/yalo_plugin_ocaml -I ./_build/install/default/lib/yalo_plugin_YALO -I ./_build/install/default/lib/yalo_plugin_FIND -I ./_build/install/default/lib/yalo_lib -I share

yalotest: build
	$(YALO_RUN) -L yalo_no_final_line.ml lint

yaloyalo: build
	$(YALO_RUN) lint -p yalo

yalofind: build
	$(YALO_RUN) -L yalo_plugin_FIND lint --skip-config-warnings -w FIND $(YALO_FINAL_ARGS)

yalo_sarif:
	opam exec -- yalo lint -vv -p yalo --message-format sarif > _yalo.sarif 2> _yalo.log

sarif: build
	dune install
	$(MAKE) yalo.sarif

dune-install: build
	opam exec -- dune install

view-doc: doc
	  echo xdg-open http://127.0.0.0:8000
	  cd _drom/docs; php -S 127.0.0.0:8000